[package]
name = "extension"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
dbg-rs = { path = "../" }
windows = { version = "0.59.0", features = ["Win32_Foundation"] }
